export const consoles = [
  {
    name: "Atari 2600",
    brand: "Atari",
    year: 1977,
    desc: "O primeiro console de videogame de sucesso comercial",
    image: "/consoles/atari-2600.png",
    games: ["Pong", "Space Invaders", "Pac-Man", "Adventure"],
  },
  {
    name: "NES",
    brand: "Nintendo",
    year: 1983,
    desc: "Revitalizou a indústria de jogos após a crise de 1983",
    image: "/consoles/nes.png",
    games: ["Super Mario Bros", "The Legend of Zelda", "Metroid", "Contra"],
  },
  {
    name: "Mega Drive",
    brand: "Sega",
    year: 1988,
    desc: "Trouxe gráficos 16-bit para a era de ouro dos arcades",
    image: "/consoles/sega-genesis.jpg",
    games: ["Sonic the Hedgehog", "Shinobi", "Golden Axe", "Streets of Rage"],
  },
  {
    name: "PlayStation 1",
    brand: "Sony",
    year: 1994,
    desc: "Revolucionou os jogos com tecnologia 3D em tempo real",
    image: "/consoles/ps1.jpg",
    games: ["Final Fantasy VII", "Metal Gear Solid", "Resident Evil", "Tekken"],
  },
  {
    name: "Nintendo 64",
    brand: "Nintendo",
    year: 1996,
    desc: "Pioneiro em 3D com controle analógico revolucionário",
    image: "/consoles/nintendo-64.jpg",
    games: ["Super Mario 64", "The Legend of Zelda: OoT", "GoldenEye 007"],
  },
  {
    name: "Game Boy",
    brand: "Nintendo",
    year: 1989,
    desc: "Dominante nos jogos portáteis por duas décadas",
    image: "/consoles/game-boy.jpg",
    games: ["Tetris", "Super Mario Land", "Pokémon Red", "Donkey Kong Land"],
  },
];
